language: node_js

sudo: false

cache:
  apt: true
  yarn: true
  directories:
    - $HOME/.npm

node_js:
  - 9

script:
  - yarn test

notifications:
  email:
    on_start: never
    on_failure: always
    on_success: change
